#name: Supabase Backup
#
#on:
#  schedule:
#    - cron: "0 2 * * *" # Every day at 2:00 AM
#  workflow_dispatch: { }
#
#jobs:
#  backup:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v6
#
#      - uses: supabase/setup-cli@v1
#
#      - name: Dump DB
#        run: supabase db backup # TODO